# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-31 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_auto_20170130_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='is_viewer',
            field=models.BooleanField(default=False, verbose_name='account is viewer'),
        ),
    ]
