# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-31 17:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_camera_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 31, 17, 16, 38, 881008, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
