# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 21:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_auto_20170131_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
